name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, lint
      run: |
        npm i
        npm run build --if-present
        npm run lint
      env:
        CI: true
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "test"
        NEXT_PUBLIC_SUPABASE_URL: "http://test"
